# Generated by Django 5.1.1 on 2024-09-10 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Canceled', 'Canceled'), ('Approved', 'Approved'), ('Rejected', 'Rejected')])),
                ('authorType', models.CharField(choices=[('Organization', 'Organization'), ('User', 'User')])),
                ('version', models.PositiveIntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.employee')),
            ],
        ),
        migrations.CreateModel(
            name='BidDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.employee')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.bid')),
            ],
        ),
        migrations.CreateModel(
            name='BidReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.employee')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.bid')),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('serviceType', models.CharField(choices=[('Construction', 'Construction'), ('Delivery', 'Delivery'), ('Manufacture', 'Manufacture')])),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Closed', 'Closed')])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.employee')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BidVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Canceled', 'Canceled'), ('Approved', 'Approved'), ('Rejected', 'Rejected')])),
                ('authorType', models.CharField(choices=[('Organization', 'Organization'), ('User', 'User')])),
                ('version', models.PositiveIntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.employee')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.bid')),
                ('tenderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.tender')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='tenderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.tender'),
        ),
        migrations.CreateModel(
            name='TenderVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('serviceType', models.CharField(choices=[('Construction', 'Construction'), ('Delivery', 'Delivery'), ('Manufacture', 'Manufacture')])),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Closed', 'Closed')])),
                ('createdAt', models.DateTimeField()),
                ('version', models.PositiveIntegerField()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.employee')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.organization')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.tender')),
            ],
        ),
    ]
