# Generated by Django 5.1.1 on 2024-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_bid_biddecision_bidreview_tender_bidversion_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='biddecision',
            constraint=models.UniqueConstraint(fields=('bid', 'author'), name='unique_biddecision'),
        ),
    ]
